name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Generate light mode SVG
      - name: Generate light SVG
        uses: Platane/snk@master
        with:
          github_user_name: gl-ankit-kumar
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Generate dark mode SVG
      - name: Generate dark SVG
        uses: Platane/snk@master
        with:
          github_user_name: gl-ankit-kumar
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          args: --palette github-dark

      # Generate GIF
      - name: Generate GIF
        uses: Platane/snk@master
        with:
          github_user_name: gl-ankit-kumar
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Deploy to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout --orphan output
          git reset --hard
          git add -f dist/
          git commit -m "Deploy snake animation"
          git push origin output --force
